import type { Metadata } from "next";
import { HeroSection } from "@/components/custom/PageIntroduction";

export const metadata: Metadata = {
  title: "Anurag Bhatt Portfolio",
  description: "Generated by create next app",
  icons: ["/icons/favicon.png"],
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <>
      <HeroSection
        title="Your Tech Partner"
        subtitle={`Freelance tech services with a personal touch —\n From consulting to execution.`}
      />
      {children}
    </>
  );
}
