import type { Metadata } from "next";
import { HeroSection } from "@/components/custom/PageIntroduction";
import { Separator } from "@/components/ui/separator"

export const metadata: Metadata = {
  title: "Anurag Bhatt Portfolio",
  description: "Generated by create next app",
  icons: ['/icons/favicon.png']
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <>
        <HeroSection title="Collaborate, Create, Innovate!"
        subtitle={`I'm excited to hear your ideas.\n Let's connect and build something great.`}/>
        <Separator />
        {children}
    </>
  );
}
